# Generated by Django 5.2 on 2025-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_videoseries_video_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='thumbs/'),
        ),
    ]
