# Generated by Django 5.2 on 2025-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0003_video_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_file',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to='thumbs/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/'),
        ),
    ]
