name: Deploy Videoflix Backend

on:
  push:
    branches:
      - master  # Passe ggf. an

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_VIDEOFLIX }}

      - name: Deploy via rsync
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ christoph@v2202411136713300836.megasrv.de:/home/christoph/backends/videoflix-backend/

      - name: Write .env file on server
        run: |
          ssh -o StrictHostKeyChecking=no christoph@v2202411136713300836.megasrv.de "printf '%s\n' '${{ secrets.DOTENV_PROD }}' > /home/christoph/backends/videoflix-backend/.env"

      - name: Run remote deploy tasks
        run: |
          ssh -o StrictHostKeyChecking=no christoph@v2202411136713300836.megasrv.de << 'EOF'
            cd /home/christoph/backends/videoflix-backend
            /home/christoph/backends/videoflix-backend/venv/bin/pip install -r requirements.txt
            /home/christoph/backends/videoflix-backend/venv/bin/python manage.py migrate --noinput
            /home/christoph/backends/videoflix-backend/venv/bin/python manage.py collectstatic --noinput
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart videoflix-gunicorn
            sudo supervisorctl restart videoflix-rqworker
          EOF
